Repository Rebuild-Black-Business/RBB-Website, pull requests merged in 2020-06, with the labels that each got.

#17 README: show how to get airtable key from account settings
  README.md
  docs/images/airtable-api-key-acount-settings.png
Labels: documentation

#18 Add a "lint" command to package.json for CI
  .eslintignore
  .eslintrc.js
  .github/workflows/node.js.yml
  jest.config.js
  package-lock.json
  package.json
Labels: enhancement

#25 Add Google Tagmanager and Facebook Tracking Pixel
  gatsby-config.js
  package-lock.json
  package.json
Labels: enhancement

#34 Feature: Buttons (cta, primary, and secondary)!
  src/components/Button.js
  src/gatsby-plugin-chakra-ui/theme.js
Labels: UI, enhancement

#29 [feature] Add Resource filter
  src/components/Buttons/PrimaryButton.js
  src/components/Feeds/SupportingOrgFeed.js
  src/components/Filters/ResourceFilter.jsx
Labels: enhancement

#8 feat: Add cloudinary hooks + serverless function
  .gitignore
  README.md
  functions/.gitignore
  functions/package-lock.json
  functions/package.json
  functions/search.js
  netlify.toml
  package-lock.json
  package.json
  src/components/Image.js
  src/components/Search.js
  src/pages/index.js
Labels: wip

#42 Fix/airtable ownership
  .env.EXAMPLE
  README.md
  gatsby-config.js
  src/components/Feeds/AllyFeed.js
  src/components/Feeds/BusinessFeed.js
  src/components/Feeds/ResourceFeed.js
  src/pages/index.js
Labels: documentation

#33 Feature: ResultCard component
  package-lock.json
  package.json
  src/components/Button.js
  src/components/Card.js
  src/components/ResultCard.js
Labels: wip

#60 feat: adds Helmet component with lang attribute to all pages.
  src/components/SEO/SEO.js
  src/pages/index.js
Labels: a11y

#67 Feature/ally card
  package-lock.json
  src/components/Card.js
  src/components/Cards/AllyCard.js
  src/components/Feeds/AllyFeed.js
  src/gatsby-plugin-chakra-ui/theme.js
Labels: UI, enhancement

#61 Feature/add footer
  gatsby-config.js
  src/components/Layout.js
  src/components/SVG/Envelope.js
  src/components/SVG/Facebook.js
  src/components/SVG/Instagram.js
  src/components/SVG/Paypal.js
  src/components/SVG/Twitter.js
  src/components/SVG/index.js
  src/components/about/ContactCard.js
  src/components/footer/Copyright.js
  src/components/footer/Footer.js
  src/components/footer/FooterLinks.js
  src/components/footer/PhotoCredits.js
  src/components/footer/SocialLinks.js
  src/gatsby-plugin-chakra-ui/theme.js
Labels: wip

#68 Add Page Hero
  src/components/Feeds/AllyFeed.js
  src/components/Feeds/BusinessFeed.js
  src/components/Filters/AllyFilter.jsx
  src/components/Filters/BusinessFilter.jsx
  src/components/Headings/PageHeading.js
  src/components/Headings/PageSubtitle.js
  src/components/PageHero.js
  src/components/Pagination/Pagination.jsx
  src/components/index.js
  src/pages/allies.js
  src/templates/businesses.js
Labels: enhancement

#91 Some small lint fixes
  src/components/footer/Copyright.js
  src/components/footer/PhotoCredits.js
Labels: enhancement

#106 About Page card size responsive fixes
  src/components/about/ContactCard.js
  src/pages/about.js
Labels: bug

#111 Configure App Manifest, add Favicon
  gatsby-config.js
  package-lock.json
  package.json
  src/images/favicon.png
Labels: enhancement

#62 Fix/add arrow functionality and adjust page neighbors
  .gitignore
  src/components/Pagination/Pagination.jsx
  src/components/Svgs/PaginationArrow.js
  src/gatsby-plugin-chakra-ui/theme.js
Labels: enhancement

#164 Fix pagination error on Allies page
  src/components/Cards/AllyCard.js
  src/components/Feeds/AllyFeed.js
  src/components/Pagination/Pagination.jsx
Labels: bug

#166 Try not to break when category is missing
  src/components/ResultCard.js
  src/utils/stringUtils.js
Labels: bug

#165 Copy updates
  src/components/Feeds/AllyFeed.js
  src/constants/about.js
  src/pages/allies.js
  src/pages/index.js
Labels: enhancement

#198 Swap Google Tag Manager for Google Analytics
  gatsby-config.js
  package-lock.json
  package.json
Labels: bug

#218 Update URLs for airtable embeds
  src/components/Forms/SubmitAlly.js
  src/components/Forms/SubmitBusiness.js
Labels: enhancement

#236 Fix/cypress a11y tests
  cypress/integration/accessibility.test.js
  cypress/videos/accessibility.test.js.mp4
  cypress/videos/errorBoundary.test.js.mp4
  src/components/footer/Footer.js
  src/gatsby-plugin-chakra-ui/theme.js
Labels: a11y, test

#232 [a11y] Unset footer Navmenu from being Flex, and add explicit flex styling
  src/components/footer/FooterLinks.js
Labels: a11y

#262 Fixes a11y issues and gets Cypress tests passing
  cypress/integration/accessibility.test.js
  cypress/integration/filter.test.js
  src/components/Headings/PageHeading.js
  src/components/Headings/PageSubtitle.js
  src/components/about/ContactCard.js
  src/pages/404.js
  src/pages/about.js
  src/pages/allies.js
  src/pages/index.js
Labels: a11y, test
