Repository Rebuild-Black-Business/RBB-Website, pull requests merged in 2020-07, with the labels that each got.

#309 fallbacks for setUrlUtm function
  src/utils/urlUtils.js
Labels: bug

#307 Feature/update business submit fields
  src/components/Forms/BusinessSignUpForm.js
  src/services/AirtableServices.js
  src/utils/stateObj.js
Labels: QA, enhancement

#316 Revert "Add x-api-key to search call"
  .env.EXAMPLE
  .env.development.EXAMPLE
  src/hooks/useSearch.js
Labels: bug

#317 add x-api-key to search call
  .env.EXAMPLE
  .env.development.EXAMPLE
  src/hooks/useSearch.js
Labels: documentation, enhancement
